### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by VisineK** [tanmaysharma1337/valorant-rank-tracker-OBS#1]
Hi, 
I tried to launch your project, but from "pyinstaller ValorantTracker.spec" it doesn't work.
He told me that pyinstaller is not a keyword to launch a function. However I downloaded it.

Best regards.

**Comment by tanmaysharma1337** [comment]
Hello @VisineK ,

This usually happens when pyinstaller is not installed properly or is not added in the environment variables,

I suggest you to try this , 

go to your project folder where your .spec file is located

Then open commandline in the same directory and run this command

```
python -m PyInstaller ValorantTracker.spec
```

Make sure you do 


`pip install pyinstaller`

Before executing the above command

**Comment by tanmaysharma1337** [comment]
Hello @VisineK ,

This usually happens when the pyinstaller is not installed properly or is not added in the environment variables,

I suggest you to try this , 

go to your project folder where your .spec file is located

Then open commandline in the same directory and run this command

```
python -m PyInstaller script.py
```
